install:
  - export PKG_CONFIG_PATH="${HOME}/lib/pkgconfig:${PKG_CONFIG_PATH}"
  - export LIBRARY_PATH="${HOME}/lib:${LIBRARY_PATH}"
  - export LD_LIBRARY_PATH="${HOME}/lib:${LD_LIBRARY_PATH}"

  - LIBSODIUM_VERSION=1.0.3
  - curl -fsSL https://github.com/jedisct1/libsodium/releases/download/${LIBSODIUM_VERSION}/libsodium-${LIBSODIUM_VERSION}.tar.gz | tar -zxf -
  - pushd libsodium-${LIBSODIUM_VERSION}
  - ./configure --prefix=${HOME}
  - make install -j2
  - popd

  - ZEROMQ_VERSION=4.1.3
  - curl -fsSL http://download.zeromq.org/zeromq-${ZEROMQ_VERSION}.tar.gz | tar -zxf -
  - pushd zeromq-${ZEROMQ_VERSION}
  - ./configure --prefix=${HOME}
  - make install -j2
  - popd

language: d
